# 서버 포트 (Flask 서버와 동시에 켜도 충돌하지 않도록 8080 사용)
server.port=8080

# Spring Boot DB 연결 설정
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate 설정 (테이블 자동 생성 및 데이터 유지)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
